import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}


const myComponent = () => {
  return <h1>Hello World</h1>;
};

const myComponet2 = () => {
  return <h2>Test 1</h2>;
};

function myComponet3(){
  return <div>Tag</div>;
}